version: '3'

services:
  web:
    build: .
    restart: always
    container_name: 'recommend_app'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: 'database'
    command: mongod
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: 'mongo-express'
    restart: always
    ports:
      - 8081:8081
