# Generated by Django 2.2.12 on 2020-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('synopsis', models.TextField()),
                ('genre', models.CharField(max_length=500)),
                ('aired', models.CharField(max_length=500)),
                ('episodes', models.CharField(max_length=500)),
                ('members', models.CharField(max_length=500)),
                ('popularity', models.CharField(max_length=500)),
                ('ranked', models.CharField(max_length=500)),
                ('score', models.CharField(max_length=500)),
                ('img_url', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('name', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=500)),
                ('isbn', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('img_paths', models.CharField(max_length=500)),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbId', models.CharField(max_length=10, null=True)),
                ('Imdb_Link', models.CharField(max_length=500, null=True)),
                ('Title', models.CharField(max_length=500, null=True)),
                ('IMDB_Score', models.CharField(max_length=500, null=True)),
                ('Genre', models.CharField(max_length=500, null=True)),
                ('Poster', models.TextField()),
            ],
        ),
    ]
