# Generated by Django 2.2.12 on 2020-06-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='aired',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='members',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='popularity',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='ranked',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='uid',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='img_paths',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
